--Desafio: número de notas para diversos dias

DECLARE @DATAINICIAL DATE, @DATAFINAL DATE;
DECLARE @NUM_NOTAS INT;

SET @DATAINICIAL = '2017-01-01'
SET @DATAFINAL = '2017-01-10'

WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
	SELECT  @NUM_NOTAS = COUNT(*) FROM [NOTAS FISCAIS]
		WHERE DATA = @DATAINICIAL;

	PRINT 'Data: ' + CONVERT(VARCHAR(20), @DATAINICIAL) +
	'; Número de notas: ' + CONVERT(VARCHAR(10), @NUM_NOTAS);

	SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL);
END;


--Desafio: escreva a sequência de FIBONACCI

DECLARE @NUMERO_ANTERIOR2 INT;
DECLARE @NUMERO_ANTERIOR1 INT;
DECLARE @NUMERO_ATUAL INT;
DECLARE @SEQUENCIA INT;
DECLARE @CONTADOR_SEQUENCIA INT;

SET @SEQUENCIA = 44;
SET @CONTADOR_SEQUENCIA = 3;

SET @NUMERO_ANTERIOR2 = 0;
SET @NUMERO_ANTERIOR1 = 1;
PRINT 'POSIÇÃO 1 --> 0';
PRINT 'POSIÇÃO 2 --> 1';
WHILE @CONTADOR_SEQUENCIA <= @SEQUENCIA
BEGIN
   SET @NUMERO_ATUAL = @NUMERO_ANTERIOR2 + @NUMERO_ANTERIOR1;
   PRINT 'POSIÇÃO ' + TRIM(STR(@CONTADOR_SEQUENCIA,10,0)) + ' --> ' + TRIM(STR(@NUMERO_ATUAL, 10,0));
   SET  @NUMERO_ANTERIOR2 = @NUMERO_ANTERIOR1;
   SET @NUMERO_ANTERIOR1 = @NUMERO_ATUAL;
   SET @CONTADOR_SEQUENCIA = @CONTADOR_SEQUENCIA + 1;
END;


--Desafio: número de notas salvas em uma tabela

IF OBJECT_ID('TABELA DE NOTAS','U') IS NOT NULL
	DROP TABLE [TABELA DE NOTAS]

CREATE TABLE [TABELA DE NOTAS] (DATA DATE, NUM_NOTAS INT)

DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT

SET @DATAINICIAL = '2017-01-01'
SET @DATAFINAL = '2017-01-10'

WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL;

	INSERT INTO [TABELA DE NOTAS] (DATA, NUM_NOTAS) 
        VALUES (@DATAINICIAL, @NUMNOTAS)

    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END;

SELECT * FROM [TABELA DE NOTAS];