--Desafio: FOR decrescente

DECLARE @I INT;

SET @I = 100;

WHILE @I >= 0
BEGIN
	PRINT @I;
	SET @I = @I - 1;
END;


--Desafio: escrevendo a sequência de FIBONACCI em uma tabela

DECLARE @NUMERO_ANTERIOR2 INT;
DECLARE @NUMERO_ANTERIOR1 INT;
DECLARE @NUMERO_ATUAL INT;
DECLARE @SEQUENCIA INT;
DECLARE @CONTADOR_SEQUENCIA INT;

DECLARE @TABELA_DE_NUMEROS TABLE (SEQUENCIA INT, VALOR INT);

SET @SEQUENCIA = 44;
SET @CONTADOR_SEQUENCIA = 3;

SET @NUMERO_ANTERIOR2 = 0;
SET @NUMERO_ANTERIOR1 = 1;
INSERT INTO @TABELA_DE_NUMEROS VALUES (1,0);
INSERT INTO @TABELA_DE_NUMEROS VALUES (2,1);
WHILE @CONTADOR_SEQUENCIA <= @SEQUENCIA
BEGIN
   SET @NUMERO_ATUAL = @NUMERO_ANTERIOR2 + @NUMERO_ANTERIOR1;
   INSERT INTO @TABELA_DE_NUMEROS VALUES (@CONTADOR_SEQUENCIA, @NUMERO_ATUAL)
   SET  @NUMERO_ANTERIOR2 = @NUMERO_ANTERIOR1;
   SET @NUMERO_ANTERIOR1 = @NUMERO_ATUAL;
   SET @CONTADOR_SEQUENCIA = @CONTADOR_SEQUENCIA + 1;
END;

SELECT * FROM @TABELA_DE_NUMEROS;