--Desafio: listando todos os produtos

DECLARE @CODIGO VARCHAR(10);
DECLARE @NOME VARCHAR(50);
DECLARE @NUMERO_PRODUTOS INT;
DECLARE @I INT;

SELECT @NUMERO_PRODUTOS = COUNT(*) FROM [TABELA DE PRODUTOS];
SET @I = 1;

WHILE @I <= @NUMERO_PRODUTOS
BEGIN
        SELECT @CODIGO = X.[CODIGO DO PRODUTO], @NOME = X.[NOME DO PRODUTO]
        FROM ( SELECT Row_Number() Over (Order By [CODIGO DO PRODUTO]) as RowNum, * FROM [TABELA DE PRODUTOS]) X
        WHERE X.RowNum = @I;
        PRINT @CODIGO + ' - ' + @NOME;
        SET @I = @I + 1;
END;


--Desafio: calculando as vendas dos produtos

DECLARE @CODIGO VARCHAR(10);
DECLARE @NOME VARCHAR(50);
DECLARE @NUMERO_PRODUTOS INT;
DECLARE @I INT;
DECLARE @MES INT, @ANO INT;
DECLARE @TOTAL_VENDAS FLOAT;

SET @MES = 1;
SET @ANO = 2015;
SELECT @NUMERO_PRODUTOS = COUNT(*) FROM [TABELA DE PRODUTOS];
SET @I = 1;

WHILE @I <= @NUMERO_PRODUTOS
BEGIN
	SELECT @CODIGO = X.[CODIGO DO PRODUTO], @NOME = X.[NOME DO PRODUTO]
    FROM ( SELECT Row_Number() Over (Order By [CODIGO DO PRODUTO]) as RowNum, * FROM [TABELA DE PRODUTOS]) X
    WHERE X.RowNum = @I;

		SELECT 
		@TOTAL_VENDAS = SUM([ITENS NOTAS FISCAIS].QUANTIDADE * [ITENS NOTAS FISCAIS].[PREÇO])
		FROM [NOTAS FISCAIS] 
		INNER JOIN [ITENS NOTAS FISCAIS]
		ON [NOTAS FISCAIS].NUMERO = [ITENS NOTAS FISCAIS].NUMERO
		WHERE  [ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO] = @CODIGO
		AND YEAR([NOTAS FISCAIS].DATA) = @ANO AND MONTH([NOTAS FISCAIS].DATA) = @MES;

        PRINT 'Valor total de vendas para: ' + @CODIGO + ' - ' + @NOME +
		', No mês ' + CONVERT(VARCHAR(2), @MES) + ' e ano de ' +
		CONVERT(VARCHAR(4),@ANO) + ' foi R$' + TRIM(STR(@TOTAL_VENDAS, 15, 2));
        SET @I = @I + 1;
END;